resolve processing core from official source
processing/processing-library-template pull request #63
Opened 2024-12-04 13:08 UTC by mingness

Retire use of micycle1's repo, and point to official maven source.
remove previous repository dependencies.

2024-12-04 14:02 UTC, Stefterv requested changes

2024-12-04 14:02 UTC, Stefterv commented on build.gradle.kts
> -    maven { url = uri("https://jogamp.org/deployment/maven/") }
I think jogamp should still be in there for jogl no?

2024-12-04 14:02 UTC, Stefterv commented on build.gradle.kts
> +    compileOnly(group = "org.processing", name = "core", version = "4.3.1")
👍

2024-12-04 14:25 UTC, mingness commented on build.gradle.kts
> -    maven { url = uri("https://jogamp.org/deployment/maven/") }
hmm, I tried to build it without, and it worked. I deleted the `build` and `release` folders beforehand for good measure - do I need to delete something on my file system to check more robustly? There is nothing related to jogl in my ~/.m2 folder.

2024-12-05 10:05 UTC, Stefterv commented on build.gradle.kts
> -    maven { url = uri("https://jogamp.org/deployment/maven/") }
okay, well it doesn't hurt to leave it

2024-12-05 14:08 UTC, mingness commented on build.gradle.kts
> -    maven { url = uri("https://jogamp.org/deployment/maven/") }
Sure, I'll add it back in, but I also want to understand the situation well. It doesn't hurt, but as far as I can tell, it doesn't help? I guess, it would be needed if we ever wanted to run Processing from the template? I verified that the build requires the jogamp repository if resolving Processing with micycle1's repo, but if resolving from processing.org, the jogamp repo is not necessary.

2025-01-11 11:05 UTC, mingness commented
somehow lost track of this one. :frowning: 
@Stefterv have added the jogamp maven repo back in.

2025-01-11 11:05 UTC, Stefterv approved these changes

2025-01-11 11:13 UTC, merged